image: python:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Construyendo el proyecto..."
    - pip install -r requirements.txt


test:
  stage: test
  script:
    - echo "Testeando el proyecto..."
    - pylint test.py
    - python test.py
