name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install coverage pylint

      - name: Run tests
        run: |
          coverage run --source=. test.py
          coverage report -m > coverage_report.txt
          pylint test.py > pylint_report.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Coverage and Pylint Reports
          path: |
            coverage_report.txt
            pylint_report.txt
